# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1b2f098e4c37aeaebc91cb768dae446902e3f396698121932921b4e8f958c334f59365264a906a7e5b6238f5f01e1034993f26b279002a5b5da16683393f6d

test:
  secret_key_base: 0da7d76967a38328cc5bcce1afeeef45fe8a4654f45c110b18c61d34fd2aabce3c342276ec337e6973a20888d5a5f95c0b67cdb6be5f6545de1d3f39ffcc6f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
